# Generated by Django 2.1.1 on 2019-03-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20190327_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='loop',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=25.0, max_digits=10, null=True),
        ),
    ]
