# Generated by Django 2.1.1 on 2019-04-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20190329_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('cc_number', models.PositiveIntegerField()),
                ('exp_date', models.PositiveIntegerField()),
                ('cvc', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=25.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
