# Generated by Django 2.1.1 on 2019-04-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_auto_20190408_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyers',
            field=models.ManyToManyField(related_name='bought_tickets', to='first_app.Ticket'),
        ),
    ]
